[package]
name = "marvel_champions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
bevy-inspector-egui = "0.30.0"
bevy_embedded_assets = "0.12.0"
bevy_pkv = "0.12.0"
bevy_simple_text_input = "0.10.2"

