[package]
name = "marvel_champions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
bevy-inspector-egui = "0.31.0"
bevy_embedded_assets = "0.13.0"
bevy_pkv = "0.13.0"
bevy_simple_text_input = "0.11.0"
serde = "1.0.219"
uuid = "1.12.1"
